import { initNavbar } from './navbar.js';
import { initAssistant } from './assistant.js';
import { initContact } from './contact.js';
import { initGallery } from './gallery.js';
import { initReview } from './review.js';
import { initServices } from './services.js';
import { initFooterHours } from './footer.js';
import { initBackToTop } from './back-to-top.js';
import {initTourVirtual} from './tourVirtual.js';
import { initAnalytics } from './analytics.js';
import { initCookieBanner } from './cookie-banner.js';
initNavbar();
initAssistant();
initContact();
initGallery();
initReview();
initTourVirtual();
initFooterHours();
initServices();
initBackToTop();
initAnalytics();
initCookieBanner();